name: "Test Action: Greeter"
description: "Greet someone"
author: "dbgb"

inputs:
  USER_NAME:
    description: "The name of the person to greet"
    required: true
    default: "World"

outputs:
  TIME:
    description: "The time of the greeting"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.USER_NAME }}

branding:
  icon: "mic"
  color: "purple"
