name: "Greeter"

on: push

jobs:
  greeter-job:
    name: A job to say hello!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Greeting step
        id: greeting
        uses: ./action-a
        with:
          USER_NAME: "dbgb"
      - name: Output greeting time
        run: echo "The time was ${{steps.greeting.outputs.time}}"
